#version 450

struct MeshMetaData {
    uint indexCount;
    uint firstIndex;
    uint vertexOffset;
};

struct DrawCall 
{
    uint indexCount;
    uint instanceCount;
    uint firstIndex;
    uint vertexOffset;
    uint firstInstance;
    uint materialIndex ;
    uint meshIndex ;
    uint batchDataElementSize;
    uint lodCountPointerParent;
};

layout(push_constant) uniform PushConstants{
    uint batchCount;
};

layout(std430, binding = 0) readonly buffer MeshMetaDatas{
    MeshMetaData meshMetaData[];
};

layout(std430, binding = 1) buffer DrawCalls{
    DrawCall drawCalls[];
};

layout (local_size_x = 16, local_size_y = 1, local_size_z = 1) in;
void main()
{
	uint index = gl_GlobalInvocationID.x;
	if(index >= batchCount)
		return;
		
    MeshMetaData mesh = meshMetaData[drawCalls[index].meshIndex];

	drawCalls[index].indexCount = mesh.indexCount;
	drawCalls[index].instanceCount = 0;
	drawCalls[index].firstIndex = mesh.firstIndex;
	drawCalls[index].vertexOffset = mesh.vertexOffset;
}
