#version 450
#include "DrawCall.glsl"

struct MeshMetaData {
    vec3 boundsMin;
    float padding1;
    vec3 boundsMax;
    float padding2;
    uint indexCount;
    uint firstIndex;
    uint vertexOffset;
    float padding3;
};

layout(push_constant) uniform PushConstants { uint batchCount; };

layout(std430, binding = 0) readonly buffer MeshMetaDatas { MeshMetaData meshMetaData[]; };

layout(std430, binding = 1) buffer DrawCalls { DrawCall drawCalls[]; };

layout(local_size_x = 16, local_size_y = 1, local_size_z = 1) in;
void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= batchCount) return;

    MeshMetaData mesh = meshMetaData[drawCalls[index].meshIndex];

    drawCalls[index].indexCount = mesh.indexCount;
    drawCalls[index].instanceCount = 0;
    drawCalls[index].firstIndex = mesh.firstIndex;
    drawCalls[index].vertexOffset = mesh.vertexOffset;
}
