#version 450

struct BatchMetaData
{
    uint firstInstance;
    uint batchDataElementSize;
    uint materialIndex;
    uint meshIndex;
};

struct DrawIndexed 
{
    uint indexCount;
    uint instanceCount;
    uint firstIndex;
    uint vertexOffset;
    uint firstInstance;
};

layout(push_constant) uniform PushConstants{
    uint batchCount;
    uint objectCount;
};

// layout(std140, binding = 0) uniform CameraMatrices{
//     mat4 projection;
//     mat4 view;
//     mat4 viewProjection;
// };

layout(std430, binding = 1) readonly buffer BatchMetaDatass{
    BatchMetaData batchMetaData[];
};

// MeshMetaDAt
layout(std430, binding = 2) buffer DrawInstructions{
    DrawIndexed drawInstructions[];
};

layout(std430, binding = 3) buffer InstanceMapping{
    uint instanceMapping[];
};

// layout(std430, binding = 4) buffer BatchData{ float batchData[]; };

layout (local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
void main() 
{
    uint sourceObjectIndex = gl_GlobalInvocationID.x;
    if(sourceObjectIndex >= objectCount) return;

    uint batchID = 0;
    for(uint i = batchCount-1; i != -1U; i--)
        if(sourceObjectIndex >= batchMetaData[i].firstInstance){
            batchID = i;
            break;
        }

    uint targetObjectIndex = atomicAdd(drawInstructions[batchID].instanceCount,1) + drawInstructions[batchID].firstInstance;
    instanceMapping[targetObjectIndex] = sourceObjectIndex;
}
