#version 450
#include "DrawCall.glsl"

layout(push_constant) uniform PushConstants {
    mat4 cameraViewProjection;
    uint batchCount;
    uint objectCount;
    uint firstTransparentDrawCall;
    uint transparentDrawCallCount;
};

layout(std140, binding = 0) uniform PassData {
    mat4 lightViewProjection;
    vec3 cameraPosition;
    float padding1;
    vec3 lightDirection;
    float padding2;
    vec3 lightColor;
    float padding3;
};

layout(std430, binding = 1) buffer BatchInfos { BatchInfo batchInfo[]; };

layout(std430, binding = 2) buffer DrawCalls { DrawCall drawCalls[]; };

layout(std430, binding = 3) buffer InstanceMappings { uint instanceMapping[]; };

layout(std430, binding = 4) buffer BatchDatas { float batchData[]; };

BatchInfo GetBatchData(uint sourceObjectIndex) {
    // // Binary search.
    // uint l = 0;
    // uint r = batchCount - 1;
    // uint m = 0;
    // while (l <= r) {
    //     m = l + uint((r - l) * 0.5);
    //     if (batchInfo[m].firstObjectIndex < sourceObjectIndex) l = m + 1;
    //     else if (batchInfo[m].firstObjectIndex > sourceObjectIndex) r = m - 1;
    //     else break;
    // }

    for (int i = 0; i < batchCount; i++)
        if (batchInfo[i].firstObjectIndex > sourceObjectIndex) return batchInfo[i - 1];

    return batchInfo[batchCount - 1];
}

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
void main() {
    uint objectID = gl_GlobalInvocationID.x;
    if (objectID >= objectCount) return;

    BatchInfo batch = GetBatchData(objectID);
    uint drawCall = batch.drawCall;

    // Lod selection.
    if (batch.lods[0] != -1U) {
        uint lodCount = 1 + uint(batch.lods[1] != -1U) + uint(batch.lods[2] != -1U) + uint(batch.lods[3] != -1U);

        // TODO: Add dedicated buffer for transformation matrices and remove object data element size.
        uint dataIndex = objectID * batch.objectDataElementSize / 4;
        vec3 objectPosition = vec3(batchData[dataIndex + 12], batchData[dataIndex + 13], batchData[dataIndex + 14]);
        float d = distance(objectPosition, cameraPosition) / 100;
        uint lodIndex = min(lodCount, uint(d * lodCount));
        drawCall = batch.lods[lodIndex];
    }

    // Visibility check.
    bool isVisible = true;
    if (!isVisible) return;

    // Transparency sorting.
    if (drawCall >= firstTransparentDrawCall) {
        float farPlane = 1000;
        float cameraDistance = 0;
        uint bucketCount = 10;

        uint bucketID = uint(ceil(sqrt(cameraDistance / farPlane) * bucketCount));
        drawCall = bucketID * transparentDrawCallCount + (drawCall - firstTransparentDrawCall);
    }
    uint mappingID = atomicAdd(drawCalls[drawCall].instanceCount, 1) + drawCalls[drawCall].firstInstance;
    instanceMapping[mappingID] = objectID - batch.firstObjectIndex + batch.objectDataOffset;
}
